require "rubygems"
require "features"

current_dir = File.dirname(File.expand_path(__FILE__))

# pass in config options directly as a hash. What follows are the possible keys:
# 
# :feature_files_path 
# The path to the directory containing your plaintext user stories files
# 
# :feature_file_suffix
# A suffix to the plaintext user stories filenames. The default is .feature. Ommit the dot!
# 
# :test_cases_file
# The path to the file that holds the tests generated by features.
# 
# :features_helper
# The path to the file that will be required inside the test_cases_file. 
# 
# :feature_keyword
# The keyword that is prepended to the User Stories title. Defaults to 'Feature:'. With colon.
# 
# :scenario_keyword
# The keyword that is prepended to the Scenario or Acceptance tests titles. Defaults to 'Scenario:'. With colon.
# 
# :given_scenario_keyword
# The keyword that identifies a Scenario to be reused inside another Scenario. Defaults to 'GivenScenario:'. With colon.
# 
# :project_name
# The project name will be shown at the top of the html output. Defaults to 'Features'.

suite = RailsSuite.new({
  :feature_files_path => current_dir,
  :test_cases_file    => current_dir + "/support/test_cases_file.rb",
  :features_helper    => current_dir + "/support/features_helper.rb"
})

suite.run

results = `ruby #{suite.test_cases_file}`

puts results

suite.parse_results_and_open_in_safari(results)